const KV = 'kv-peepsdb';

const GITHUB_CLIENT_ID = 'GITHUB-CLIENT-ID';
const GITHUB_CLIENT_SECRET = 'GITHUB-CLIENT-SECRET';

const GOOGLE_CLIENT_ID = 'GOOGLE-CLIENT-ID';
const GOOGLE_CLIENT_SECRET = 'GOOGLE-CLIENT-SECRET';

const MICROSOFT_CLIENT_ID = 'MICROSOFT-CLIENT-ID';
const MICROSOFT_CLIENT_SECRET = 'MICROSOFT-CLIENT-SECRET';

const MONGO_URI = 'MONGO-URI';
const JWT_SECRET = 'JWT-SECRET';
const BACKEND_URL = 'BACKEND-URL';
const FRONTEND_URL = 'FRONTEND-URL';
const PORT = 'BE-PORT';

module.exports = {
  KV,
  GITHUB_CLIENT_SECRET,
  GITHUB_CLIENT_ID,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  MICROSOFT_CLIENT_ID,
  MICROSOFT_CLIENT_SECRET,
  MONGO_URI,
  JWT_SECRET,
  BACKEND_URL,
  FRONTEND_URL,
  PORT,
};
